[package]
name = "algebra-matrix2x2"
version = "0.1.0"
authors = ["Zach Barnes <zach.c.barnes@gmail.com>"]

[lib]
crate-type = ["cdylib"]
path = "calculator.rs"

[dependencies]
nalgebra = { version = "0.20" }